/** Rutas centralizadas del panel (todo bajo /dashboard comparte layout). */
export const ROUTES = {
  login: "/",
  dashboard: "/dashboard",
  home: "/dashboard",
  infoCampo: "/dashboard/info-campo",
  solicitudServicio: "/dashboard/solicitud-servicio",
  solicitudServicioCliente: (idCliente) => `/dashboard/solicitud-servicio/${idCliente}`,
  planMuestreoPaso: (n) => `/dashboard/plan-muestreo/paso-${n}`,
  gestionUsuarios: "/dashboard/gestion-usuarios",
  gestionClientes: "/dashboard/gestion-clientes",
  gestionLaboratorios: "/dashboard/gestion-laboratorios",
  formatosOrdenServicio: "/dashboard/formatos-orden-servicio",
  catalogos: "/dashboard/catalogos",
  catalogosCargos: "/dashboard/catalogos/cargos",
  catalogosDepartamentos: "/dashboard/catalogos/departamentos",
  catalogosFuentes: "/dashboard/catalogos/fuentes",
  catalogosMatriz: "/dashboard/catalogos/matriz",
  catalogosMediosRecepcion: "/dashboard/catalogos/medios-recepcion",
  catalogosMunicipios: "/dashboard/catalogos/municipios",
  catalogosPreservantes: "/dashboard/catalogos/preservantes",
  catalogosServicios: "/dashboard/catalogos/servicios",
  catalogosTiposClientes: "/dashboard/catalogos/tipos-clientes",
  catalogosGruposAnalisis: "/dashboard/catalogos/grupos-analisis",
  catalogosTecnicasAnalisis: "/dashboard/catalogos/tecnicas-analisis",
  catalogosTiposMuestreo: "/dashboard/catalogos/tipos-muestreo",
  catalogosEquiposMuestreo: "/dashboard/catalogos/equipos-muestreo",
};
