/** Rutas centralizadas del panel (todo bajo /dashboard comparte layout). */
export const ROUTES = {
  login: "/",
  dashboard: "/dashboard",
  home: "/dashboard",
  infoCampo: "/dashboard/info-campo",
  infoCampoNueva: "/dashboard/info-campo/nueva",
  infoCampoEditar: (id) => `/dashboard/info-campo/editar/${id}`,
  solicitudServicio: "/dashboard/solicitud-servicio",
  solicitudServicioCliente: (idCliente) => `/dashboard/solicitud-servicio/${idCliente}`,
  solicitudServicioEditar: (id) => `/dashboard/solicitud-servicio/editar/${id}`,
  planMuestreo: "/dashboard/plan-muestreo",
  planMuestreoPaso: (n) => `/dashboard/plan-muestreo/paso-${n}`,
  gestionUsuarios: "/dashboard/gestion-usuarios",
  gestionClientes: "/dashboard/gestion-clientes",
  gestionLaboratorios: "/dashboard/gestion-laboratorios",
  formatosOrdenServicio: "/dashboard/formatos-orden-servicio",
  formatosOrdenServicioNueva: "/dashboard/formatos-orden-servicio/nueva",
  formatosOrdenServicioNuevaFromSolicitud: (idSolicitud) =>
    `/dashboard/formatos-orden-servicio/nueva/${idSolicitud}`,
  formatosOrdenServicioEditar: (id) => `/dashboard/formatos-orden-servicio/${id}/editar`,
  proformas: "/dashboard/proformas",
  nuevaProforma: "/dashboard/proformas/nueva",
  nuevaProformaFromSolicitud: (idSolicitud) => `/dashboard/proformas/nueva/${idSolicitud}`,
  catalogos: "/dashboard/catalogos",
  catalogosCargos: "/dashboard/catalogos/cargos",
  catalogosDepartamentos: "/dashboard/catalogos/departamentos",
  catalogosFuentes: "/dashboard/catalogos/fuentes",
  catalogosMatriz: "/dashboard/catalogos/matriz",
  catalogosMuestras: "/dashboard/catalogos/muestras",
  catalogosMediosRecepcion: "/dashboard/catalogos/medios-recepcion",
  catalogosMunicipios: "/dashboard/catalogos/municipios",
  catalogosPreservantes: "/dashboard/catalogos/preservantes",
  catalogosServicios: "/dashboard/catalogos/servicios",
  catalogosTiposClientes: "/dashboard/catalogos/tipos-clientes",
  catalogosGruposAnalisis: "/dashboard/catalogos/grupos-analisis",
  catalogosTecnicasAnalisis: "/dashboard/catalogos/tecnicas-analisis",
  catalogosTiposMuestreo: "/dashboard/catalogos/tipos-muestreo",
  catalogosEquiposMuestreo: "/dashboard/catalogos/equipos-muestreo",
  catalogosAnalisis: "/dashboard/catalogos/analisis",
  // Cadena de custodia (Fase 3).
  custodia: "/dashboard/custodia",
  custodiaNueva: "/dashboard/custodia/nueva",
  custodiaEditar: (id) => `/dashboard/custodia/editar/${id}`,
  // Formatos de ensayo y captura de resultados (Fase 3).
  ensayos: "/dashboard/ensayos",
  ensayoNuevo: "/dashboard/ensayos/nuevo",
  ensayoEditar: (id) => `/dashboard/ensayos/editar/${id}`,
};
